[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "cht_nesting"
description = "Toolkit for nesting coastal hydrodynamic and wave models"
readme = "readme.md"
authors = [
    {name = "Maarten van Ormondt", email = "maarten.vanormondt@deltares-usa.us"},
    {name = "Floortje Roelvink", email = "floortje.roelvink@deltares.nl"},
]
license = {text = "MIT"}
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Hydrology",
]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "geopandas",
    "pyproj",
    "shapely",
    "scipy",
    "xarray",
    "netCDF4",
    "cht_utils @ git+https://github.com/jprsco/cht_utils_ssph.git",
    "cht_tide @ git+https://github.com/jprsco/cht_tide_ssph.git",
]
dynamic = ["version"]

[project.optional-dependencies]
tests = ["pytest", "pytest-cov"]

[tool.setuptools]
zip-safe = true

[tool.setuptools.dynamic]
version = {attr = "cht_nesting.__version__"}

[tool.setuptools.packages.find]
include = ["cht_nesting*"]

[tool.setuptools.package-data]
"*" = ["*.yml"]

[tool.pytest.ini_options]
addopts = "--cov cht_nesting --cov-report xml"
testpaths = ["tests"]
pythonpath = ["tests"]
